In [17]:
import pandas as pd
import numpy as np
import requests

In [2]:
participacoes_acionarias = pd.read_csv(
    'https://dadosabertos.bndes.gov.br/dataset/68a85772-df73-4c8b-8b8c-398f494fcca8/resource/10ff2d60-02d1-4619-8e42-24fc2a5927dd/download/renda-variavel-participacoes-acionarias-historico-da-carteira.csv',
    sep=';',
    decimal=',')
participacoes_acionarias.head()

,sigla,razao_social,cnpj,tipo_de_ativo,ano,setor_de_atividade,total_pp,on_pp,pn_pp,aberta_fechada,acordo_de_acionistas_em_vigor,indicado_para_conselho_de_administracao,indicado_para_conselho_fiscal
0,ABICO,ABICO - CIA. DE INVESTIMENTOS ÁRABE E BRASILEIRO,42.470.443/0001-96,PARTICIPAÇÃO ACIONÁRIA,2024,OUTROS SETORES,35.0,35.0,0.0,FECHADA,NÃO,NÃO,NÃO
1,ABICO,ABICO - CIA. DE INVESTIMENTOS ÁRABE E BRASILEIRO,42.470.443/0001-96,PARTICIPAÇÃO ACIONÁRIA,2023,OUTROS SETORES,35.0,35.0,0.0,FECHADA,NÃO,NÃO,NÃO
2,ABICO,ABICO - CIA. DE INVESTIMENTOS ÁRABE E BRASILEIRO,42.470.443/0001-96,PARTICIPAÇÃO ACIONÁRIA,2022,OUTROS SETORES,35.0,35.0,0.0,FECHADA,NÃO,NÃO,NÃO
3,ABICO,ABICO - CIA. DE INVESTIMENTOS ÁRABE E BRASILEIRO,42.470.443/0001-96,PARTICIPAÇÃO ACIONÁRIA,2021,OUTROS SETORES,35.0,35.0,0.0,FECHADA,NÃO,NÃO,NÃO
4,ABICO,ABICO - CIA. DE INVESTIMENTOS ÁRABE E BRASILEIRO,42.470.443/0001-96,PARTICIPAÇÃO ACIONÁRIA,2020,OUTROS SETORES,35.0,35.0,0.0,FECHADA,NÃO,NÃO,NÃO

In [3]:
participacoes_acionarias.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2287 entries, 0 to 2286
Data columns (total 13 columns):
 #   Column                                   Non-Null Count  Dtype
---  ------                                   --------------  -----
 0   sigla                                    2287 non-null   object
 1   razao_social                             2287 non-null   object
 2   cnpj                                     2286 non-null   object
 3   tipo_de_ativo                            2287 non-null   object
 4   ano                                      2287 non-null   int64
 5   setor_de_atividade                       2283 non-null   object
 6   total_pp                                 2264 non-null   float64
 7   on_pp                                    2264 non-null   float64
 8   pn_pp                                    2264 non-null   float64
 9   aberta_fechada                           2286 non-null   object
 10  acordo_de_acionistas_em_vigor            2287 non-null   object
 11  indicado_para_conselho_de_administracao  2287 non-null   object
 12  indicado_para_conselho_fiscal            2287 non-null   object
dtypes: float64(3), int64(1), object(9)
memory usage: 232.4+ KB

In [4]:
participacoes_acionarias['ano'].value_counts()

ano
2011    172
2009    158
2012    157
2013    155
2010    154
2008    145
2007    143
2014    133
2006    130
2015    125
2016    124
2017    108
2018    101
2019     87
2020     87
2021     83
2023     75
2022     75
2024     75
Name: count, dtype: int64

In [5]:
participacoes_acionarias.sigla.unique()

array(['ABICO', 'AÇOS VILLARES', 'AES BRASIL ENER', 'AES COMM RJ',
       'AES ELPA', 'AES TE', 'AES TH', 'AES TIETÊ', 'AES TIETÊ ENERG',
       'AES URUGUAIANA', 'ÁGUIA', 'ALCOOLQUÍMICA', 'ALFATEST', 'ALTUS',
       'ALUPAR', 'AMATA', 'AMATA URBEM', 'AMBEV', 'AMERICANAS',
       'AMERICEL', 'ARACRUZ', 'ARCELORMITTAL', 'AUTEL', 'BANCO DO BRASIL',
       'BCPAR', 'BEMATECH', 'BERTIN', 'BIO FILL', 'BIOMM', 'BIONNOVATION',
       'BLOCKBIT', 'BM&F BOVESPA', 'BNB', 'BOM GOSTO', 'BOMBRIL',
       'BR MALLS', 'BRADESCO', 'BRADESPAR', 'BRASAGRO', 'BRASIL FOODS',
       'BRASIL TEL PART', 'BRASILIANA PART', 'BRASILINTERPART', 'BRASKEM',
       'BRASPÉROLA', 'BRICLOG', 'BRQ', 'CADAM', 'CARBOMIL', 'CASA ANGLO',
       'CASAL', 'CBD', 'CBO HOLDING', 'CBPAK', 'CCR', 'CCX', 'CEAL',
       'CEG', 'CEMIG', 'CEMIG DISTRIB.', 'CEMIG GT', 'CESP', 'CETIP S.A.',
       'CHAPECÓ', 'CI&T', 'CIELO', 'CIMETAL', 'CIPHER', 'CLAMPER',
       'CLARO', 'COMTEX', 'COMTRAFO', 'COPASA', 'COPEL', 'COSAN',
       'COSAN LOG', 'COTEMINAS', 'CPFL ENERGIA', 'CRP CADERI', 'CRSEC',
       'CSN', 'CTC', 'CTC/RJ', 'CTTU/RECIFE', 'CTX', 'CYRELA REALTY',
       'DETEN', 'DIGITEL', 'EBP', 'ECORODOVIAS INF', 'ELEBRA',
       'ELETROACRE', 'ELETROBRÁS', 'ELETROPAULO', 'ELETROPAULO TEL',
       'EMAE', 'EMBRAER', 'EMBRATEL OPER.', 'EMBRATEL PART.', 'ENAUTA',
       'ENB', 'ENERGISA', 'ENERGISA MT', 'ENEVA', 'ENGIE BRASIL',
       'EQUATORIAL', 'ERB', 'FD ETF ICO2', 'FIAGRIL PART.', 'FIBRIA',
       'FOTON', 'GAFISA', 'GENOA', 'GERDAU', 'GERDAU MET.', 'GOL',
       'GRANBIO', 'GRANO', 'GRAÚNA', 'GRUPO A', 'HIDROVIAS',
       'HIGH BRIDGE', 'HOSPITAL FÊMINA', 'HYPERA', 'IBEMA',
       'IGUA SANEAMENTO', 'INDEPENDÊNCIA', 'INEPAR', 'INEPAR ENERGIA',
       'IOCHPE', 'ITAITUBA', 'ITAÚ UNIBANCO', 'ITAUCORP', 'ITAÚSA',
       'ITAUTINGA', 'IVESA', 'JBS', 'KEPLER WEBER', 'KLABIN', 'KLICK NET',
       'KOBLITZ', 'KOSMOS', 'LATINA', 'LBR', 'LDC-BIOENERGIA', 'LDC-SEV',
       'LIFEMED', 'LIGHT', 'LINX', 'LIQ. PART', 'LLX', 'LOG', 'LORENZ',
       'LUPATECH', 'MADEF', 'MAGNESITA REFR.', 'MAGNESITA S.A.',
       'MANGELS', 'MARCOPOLO', 'MARFRIG', 'MARLIM', 'MARLIMPAR',
       'MECTRON', 'METALFRIO', 'METANOR', 'METRÔ/SP', 'MMX MINERAÇÃO',
       'MOBIGROUP', 'MRV', 'MUNDIAL S.A.', 'MWI (ZUM NET)', 'NANOCORE',
       'NATURA', 'NESBER', 'NET', 'NETUNO', 'NILZA', 'NORTEC',
       'NOVA AMERICA', 'NOVADATA', 'NOVAMARLIMPAR', 'NUTRELLA',
       'NUTRIPLANT', 'OCEANA', 'ODEBRECHT AGRO', 'OGP', 'OI',
       'OPENCOMMERCE', 'ORBISAT', 'OTP', 'OURO FINO PAR',
       'OURO FINO SAUDE', 'PADTEC', 'PADTEC HOLDING', 'PARANAPANEMA',
       'PDG REALTY', 'PETROBRAS', 'POLY EASY', 'PORTX', 'PRATICA',
       'PRÁTICA PAR', 'PROCABLE', 'PROGEN', 'PRONOR', 'QUALITY SOFT',
       'RECEPTA', 'REDE ENERGIA', 'REDECARD', 'REIVAX', 'RELASTOMER',
       'RENNER', 'RENOVA', 'RFFSA', 'RIOPOL', 'ROCHA', 'ROMI', 'ROOSTER',
       'ROSSI', 'RUMO', 'RUMO LOGÍSTICA', 'SAM', 'SANTANDER',
       'SÃO MARTINHO', 'SAPORE', 'SBCE', 'SETAL', 'SINQIA', 'SISA',
       'SOROSISTEM', 'SOUZA CRUZ', 'SPRINGER', 'SPRINGS GLOBAL', 'STARA',
       'SUNEW', 'SUZANO', 'TAESA', 'TAUM CHEMIE', 'TBM', 'TECNORED',
       'TECPAR', 'TECSIS', 'TEIKON', 'TELEBRÁS', 'TELEFÔNICA BR',
       'TELEMAR N LESTE', 'TELEMAR PART', 'TELEMIG CEL PAR',
       'TELEMIG CELULAR', 'TIM PARTICIP.', 'TNLP (TELEMAR)', 'TOPSPORTS',
       'TOTVS', 'TRANS. PAULISTA', 'TRANSNORDESTINA', 'TRANSURB',
       'TREVISA', 'TRIUNFO', 'TUPY', 'UNITEC', 'USIMINAS', 'VALE',
       'VALEPAR', 'VALLÉE', 'VBC ENERGIA', 'VICUNHA TÊXTIL', 'VIGOR',
       'VIVO', 'VLI', 'VSE', 'VULCABRÁS', 'ZENVIA'], dtype=object)

In [6]:
participacoes_acionarias[participacoes_acionarias['ano'] == 2021].sigla.unique()

array(['ABICO', 'AES BRASIL ENER', 'AES ELPA', 'ALCOOLQUÍMICA', 'AMATA',
       'AMATA URBEM', 'BIOMM', 'BLOCKBIT', 'BOMBRIL', 'BRASAGRO',
       'BRASILIANA PART', 'BRASILINTERPART', 'BRASPÉROLA', 'BRQ', 'CADAM',
       'CARBOMIL', 'CASA ANGLO', 'CASAL', 'CEG', 'CEMIG', 'CHAPECÓ',
       'COPASA', 'COPEL', 'COTEMINAS', 'CSN', 'CTC', 'CTC/RJ',
       'CTTU/RECIFE', 'DETEN', 'EBP', 'ELEBRA', 'ELETROBRÁS', 'EMBRAER',
       'ENERGISA', 'ENGIE BRASIL', 'ERB', 'GRANBIO', 'HIDROVIAS',
       'IGUA SANEAMENTO', 'INDEPENDÊNCIA', 'IOCHPE', 'ITAITUBA',
       'ITAUTINGA', 'JBS', 'KOSMOS', 'LBR', 'LIFEMED', 'LORENZ', 'MADEF',
       'METANOR', 'METRÔ/SP', 'NESBER', 'NETUNO', 'NILZA', 'NOVA AMERICA',
       'NOVADATA', 'OCEANA', 'OI', 'OTP', 'OURO FINO SAUDE',
       'PADTEC HOLDING', 'PARANAPANEMA', 'PETROBRAS', 'PRATICA', 'PROGEN',
       'QUALITY SOFT', 'RECEPTA', 'RENOVA', 'ROCHA', 'SAM', 'SPRINGER',
       'SPRINGS GLOBAL', 'STARA', 'SUNEW', 'TAUM CHEMIE', 'TBM',
       'TRANSNORDESTINA', 'TREVISA', 'TRIUNFO', 'TUPY', 'UNITEC', 'VLI',
       'VULCABRÁS'], dtype=object)

In [7]:
brasileirao = pd.read_excel('https://github.com/LucasSerra/EBAC-parte-1/raw/main/mod-4/input/campeonato-brasileiro-full.xlsx')

In [8]:
brasileirao.head()

,Rodada,Data,Horário,Dia,Mandante,Visitante,Vencedor,Arena,Mandante Placar,Visitante Placar,Estado Mandante,Estado Visitante,Estado Vencedor
0,1,2000-07-29,16h00,Sábado,Fluminense,Bahia,Fluminense,Maracanã,2,0,RJ,BA,RJ
1,1,2000-07-29,16h00,Sábado,Vasco,Sport,Sport,São Januário,0,2,RJ,PE,PE
2,1,2000-07-29,16h00,Sábado,Vitória,Palmeiras,Vitória,Barradão,4,1,ES,SP,ES
3,1,2000-07-30,17h00,Domingo,Botafogo-RJ,Atlético-MG,-,Caio Martins,0,0,RJ,MG,-
4,1,2000-07-30,18h30,Domingo,Juventude,Flamengo,-,Alfredo Jaconi,1,1,RS,RJ,-

In [9]:
brasileirao.dtypes

Rodada                      object
Data                datetime64[ns]
Horário                     object
Dia                         object
Mandante                    object
Visitante                   object
Vencedor                    object
Arena                       object
Mandante Placar              int64
Visitante Placar             int64
Estado Mandante             object
Estado Visitante            object
Estado Vencedor             object
dtype: object

In [10]:
brasileirao.Vencedor.value_counts()

Vencedor
-                  2148
São Paulo           366
Santos              333
Grêmio              322
Internacional       322
Cruzeiro            322
Flamengo            319
Corinthians         306
Athlético-PR        306
Fluminense          306
Atlético-MG         302
Palmeiras           294
Vasco               226
Goiás               223
Botafogo-RJ         210
Coritiba            194
Vitória             152
Figueirense         151
Ponte Preta         149
Sport               139
Bahia               135
Paraná              104
São Caetano         103
Juventude            96
Chapecoense          69
Guarani              63
Fortaleza            61
Portuguesa           57
Avaí                 57
Ceará                54
Náutico              54
Atlético-GO          51
Criciúma             50
Paysandu             50
América-MG           38
Botafogo-rj          26
Santa Cruz           25
Gama                 21
Bragantino           13
Barueri              12
Santo André          11
Brasiliense          10
Ipatinga              9
CSA                   8
Grêmio Prudente       7
Joinville             7
SANTOS                6
Botafogo-SP           6
CRUZEIRO              4
VASCO                 4
FLUMINENSE            4
América-RN            4
CORINTHIANS           3
SPORT                 2
FLAMENGO              1
PONTE PRETA           1
INTERNACIONAL         1
PALMEIRAS             1
portuguesa            1
Name: count, dtype: int64

In [11]:
cond = (brasileirao['Data'] >= '2020-01-01')& (brasileirao['Data'] <= '2021-02-26')
cond

0       False
1       False
2       False
3       False
4       False
        ...
8314     True
8315     True
8316     True
8317     True
8318     True
Name: Data, Length: 8319, dtype: bool

In [12]:
brasileirao[cond]['Vencedor'].value_counts()

Vencedor
-                108
Flamengo          21
Atlético-MG       20
Internacional     20
São Paulo         18
Fluminense        18
Palmeiras         15
Athlético-PR      15
Grêmio            14
Santos            14
Ceará             14
Bragantino        13
Corinthians       13
Atlético-GO       12
Bahia             12
Sport             12
Vasco             10
Fortaleza         10
Goiás              9
Coritiba           7
Botafogo-RJ        5
Name: count, dtype: int64

In [13]:
brasileirao.Arena.value_counts()

Arena
Maracanã             626
Mineirão             466
Morumbi              407
Beira Rio            352
Vila Belmiro         340
                    ...
Romildo Ferreira       1
Vivaldo Lima           1
Pedro Pedrossian       1
Antônio Guimarães      1
Plácido Castelo        1
Name: count, Length: 114, dtype: int64

In [16]:
!pip install requests

Requirement already satisfied: requests in /usr/local/lib/python3.10/dist-packages (2.32.3)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests) (2.2.3)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests) (2024.8.30)

In [19]:
url = 'http://apidatalake.tesouro.gov.br/ords/sadipem/tt/pvl?uf=SP&tipo_interessado=Estado'
r = requests.get(url)